---
- name: Accept SSH fingerprints for lab servers
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Ensure local .ssh directory exists
      file:
        path: "{{ lookup('env', 'HOME') }}/.ssh"
        state: directory
        mode: "0700"

    - name: Add SSH fingerprints to known_hosts
      known_hosts:
        name: "[{{ hostvars[item].ansible_host }}]:{{ hostvars[item].ansible_port }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -p ' ~ hostvars[item].ansible_port ~ ' ' ~ hostvars[item].ansible_host) }}"
        path: "{{ lookup('env', 'HOME') }}/.ssh/known_hosts"
        state: present
      loop: "{{ groups['lab_servers'] }}"
